# Generated by Django 5.1.3 on 2024-12-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="youtube_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
