# Generated by Django 5.1.3 on 2024-12-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_post_youtube_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="song_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="song_title",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
