# Generated by Django 5.1.3 on 2024-11-28 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="date_published",
            new_name="date_created",
        ),
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.TextField(default="Default summary"),
        ),
    ]
